import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { server } from '../config'
import { AlbumFullInfo } from '../utils/types'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [albumList, setAlbumList] = useState([])
  useEffect(() => {
    axios.get(`${server}/api/albums`).then((results) => {
      setAlbumList(results.data.sort(sortAlphabetically))
    })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">MA-Records</h1>
      </main>
    </>
  )
}

function sortAlphabetically(a: AlbumFullInfo, b: AlbumFullInfo) {
  return a.artist.toLowerCase().localeCompare(b.artist.toLowerCase())
}
